// <auto-generated />
using System;
using Catalde.Pedidos.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalde.Pedidos.Infrastructure.Migrations
{
    [DbContext(typeof(PedidoDbContext))]
    partial class PedidoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalde.Pedidos.Domain.Entities.Ocorrencia", b =>
                {
                    b.Property<int>("IdOcorrencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOcorrencia"));

                    b.Property<DateTime>("HoraOcorrencia")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IndFinalizadora")
                        .HasColumnType("bit");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoOcorrencia")
                        .HasColumnType("int");

                    b.HasKey("IdOcorrencia");

                    b.HasIndex("PedidoId");

                    b.ToTable("Ocorrencias", (string)null);
                });

            modelBuilder.Entity("Catalde.Pedidos.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<DateTime>("HorarioPedido")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IndEntregue")
                        .HasColumnType("bit");

                    b.HasKey("IdPedido");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("Catalde.Pedidos.Domain.Entities.Ocorrencia", b =>
                {
                    b.HasOne("Catalde.Pedidos.Domain.Entities.Pedido", null)
                        .WithMany("Ocorrencias")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Catalde.Pedidos.Domain.Entities.Pedido", b =>
                {
                    b.OwnsOne("Catalde.Pedidos.Domain.ValueObjects.NumeroPedido", "NumeroPedido", b1 =>
                        {
                            b1.Property<int>("PedidoIdPedido")
                                .HasColumnType("int");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("NumeroPedido");

                            b1.HasKey("PedidoIdPedido");

                            b1.ToTable("Pedidos");

                            b1.WithOwner()
                                .HasForeignKey("PedidoIdPedido");
                        });

                    b.Navigation("NumeroPedido")
                        .IsRequired();
                });

            modelBuilder.Entity("Catalde.Pedidos.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Ocorrencias");
                });
#pragma warning restore 612, 618
        }
    }
}
